name: NodeJS 18
on:
  workflow_call:

jobs:
  build-and-push-18:
    secrets: inherit
    uses: ./.github/workflows/wf_buildandpush.yaml
    with:
      nodejs_version: "v18.19.0"
      tags: "groundhog2k/distroless-nodejs:18, groundhog2k/distroless-nodejs:18.19.0"
