name: Pull request

on:
  pull_request:

jobs:
  verify-and-scan-18:
    permissions:
      security-events: write
    uses: ./.github/workflows/wf_verifyandscan.yaml
    with:
      nodejs_version: "v18.19.0"

  verify-and-scan-20:
    permissions:
      security-events: write  
    uses: ./.github/workflows/wf_verifyandscan.yaml
    with:
      nodejs_version: "v20.10.0"
