on:
  push:
    branches:
      - main

jobs:
  build-and-push-18:
    secrets: inherit
    uses: ./.github/workflows/nodejs18.yaml

  build-and-push-20:
    secrets: inherit
    uses: ./.github/workflows/nodejs20.yaml
