on: [pull_request]

jobs:
  verify-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker build . -t groundhog2k/distroless-nodejs:verify
      - uses: Azure/container-scan@v0
        with:
          image-name: groundhog2k/distroless-nodejs:verify
